# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import transport_pb2 as transport__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in transport_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PublicTransportStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBusArrival = channel.unary_unary(
                '/transport.PublicTransport/GetBusArrival',
                request_serializer=transport__pb2.BusArrivalRequest.SerializeToString,
                response_deserializer=transport__pb2.BusArrivalResponse.FromString,
                _registered_method=True)
        self.GetBusServiceInfo = channel.unary_unary(
                '/transport.PublicTransport/GetBusServiceInfo',
                request_serializer=transport__pb2.BusServiceRequest.SerializeToString,
                response_deserializer=transport__pb2.BusServiceResponse.FromString,
                _registered_method=True)


class PublicTransportServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBusArrival(self, request, context):
        """Get bus arrival timings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBusServiceInfo(self, request, context):
        """Get Bus Info details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PublicTransportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBusArrival': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusArrival,
                    request_deserializer=transport__pb2.BusArrivalRequest.FromString,
                    response_serializer=transport__pb2.BusArrivalResponse.SerializeToString,
            ),
            'GetBusServiceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusServiceInfo,
                    request_deserializer=transport__pb2.BusServiceRequest.FromString,
                    response_serializer=transport__pb2.BusServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transport.PublicTransport', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transport.PublicTransport', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PublicTransport(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBusArrival(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transport.PublicTransport/GetBusArrival',
            transport__pb2.BusArrivalRequest.SerializeToString,
            transport__pb2.BusArrivalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBusServiceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transport.PublicTransport/GetBusServiceInfo',
            transport__pb2.BusServiceRequest.SerializeToString,
            transport__pb2.BusServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
